DEFINE USER = &&1
DEFINE LOCATION =  &&2

SET SERVEROUTPUT ON
DECLARE
    data_sql VARCHAR2(4000);
	index_sql VARCHAR2(4000);
    data_name VARCHAR2(500) := '&&USER'||'_DATA';
    data_file_name VARCHAR2(500) := '&&LOCATION'||'\'||data_name||'.dbf';
	index_name VARCHAR2(500) := '&&USER'||'_INDEX';
    index_file_name VARCHAR2(500) := '&&LOCATION'||'\'||index_name||'.dbf';
BEGIN
    data_sql:='CREATE SMALLFILE TABLESPACE '||data_name||' DATAFILE '''||data_file_name||''' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 10G EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO';
	index_sql:='CREATE SMALLFILE TABLESPACE '||index_name||' DATAFILE '''||index_file_name||''' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 10G EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO';
    EXECUTE IMMEDIATE data_sql;
    EXECUTE IMMEDIATE index_sql;
END;
/ 
SET SERVEROUTPUT OFF

UNDEFINE USER
UNDEFINE LOCATION