DEFINE USERNAME = &&1
SET SERVEROUTPUT ON

DECLARE
    data_sql VARCHAR2(4000);
	index_sql VARCHAR2(4000);
    data_tbs_name VARCHAR2(500) := '&&USERNAME'||'_DATA';
	index_tbs_name VARCHAR2(500) := '&&USERNAME'||'_INDEX';
BEGIN
    data_sql:='DROP TABLESPACE '||data_tbs_name||' INCLUDING CONTENTS AND DATAFILES';
	index_sql:='DROP TABLESPACE '||index_tbs_name||' INCLUDING CONTENTS AND DATAFILES';
    EXECUTE IMMEDIATE data_sql;
    EXECUTE IMMEDIATE index_sql;
END;
/ 

SET SERVEROUTPUT OFF
UNDEFINE USERNAME

